app_metrics/urls.py
from django.conf.urls import *

from app_metrics.views import *

urlpatterns = patterns('',
        url(
            regex   = r'^reports/$',
            view    = metric_report_view,
            name    = 'app_metrics_reports',
            ),
    )

app_metrics/models.py
import datetime

from django.db import models, IntegrityError
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _

from app_metrics.compat import User


class Metric(models.Model):
    """ The type of metric we want to store """
    name = models.CharField(_('name'), max_length=50)
    slug = models.SlugField(_('slug'), unique=True, max_length=60, db_index=True)

    class Meta:
        verbose_name = _('metric')
        verbose_name_plural = _('metrics')

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id and not self.slug:
            self.slug = slugify(self.name)
            i = 0
            while True:
                try:
                    return super(Metric, self).save(*args, **kwargs)
                except IntegrityError:
                    i += 1
                    self.slug = "%s_%d" % (self.slug, i)
        else:
            return super(Metric, self).save(*args, **kwargs)


class MetricSet(models.Model):
    """ A set of metrics that should be sent via email to certain users """
    name = models.CharField(_('name'), max_length=50)
    metrics = models.ManyToManyField(Metric, verbose_name=_('metrics'))
    email_recipients = models.ManyToManyField(User, verbose_name=_('email recipients'))
    no_email = models.BooleanField(_('no e-mail'), default=False)
    send_daily = models.BooleanField(_('send daily'), default=True)
    send_weekly = models.BooleanField(_('send weekly'), default=False)
    send_monthly = models.BooleanField(_('send monthly'), default=False)

    class Meta:
        verbose_name = _('metric set')
        verbose_name_plural = _('metric sets')

    def __unicode__(self):
        return self.name


class MetricItem(models.Model):
    """ Individual metric items """
    metric = models.ForeignKey(Metric, verbose_name=_('metric'))
    num = models.IntegerField(_('number'), default=1)
    created = models.DateTimeField(_('created'), default=datetime.datetime.now)

    class Meta:
        verbose_name = _('metric item')
        verbose_name_plural = _('metric items')

    def __unicode__(self):
        return _("'%(name)s' of %(num)d on %(created)s") % {
            'name': self.metric.name,
            'num': self.num,
            'created': self.created
        }


class MetricDay(models.Model):
    """ Aggregation of Metrics on a per day basis """
    metric = models.ForeignKey(Metric, verbose_name=_('metric'))
    num = models.BigIntegerField(_('number'), default=0)
    created = models.DateField(_('created'), default=datetime.date.today)

    class Meta:
        verbose_name = _('day metric')
        verbose_name_plural = _('day metrics')

    def __unicode__(self):
        return _("'%(name)s' for '%(created)s'") % {
            'name': self.metric.name,
            'created': self.created
        }


class MetricWeek(models.Model):
    """ Aggregation of Metrics on a weekly basis """
    metric = models.ForeignKey(Metric, verbose_name=_('metric'))
    num = models.BigIntegerField(_('number'), default=0)
    created = models.DateField(_('created'), default=datetime.date.today)

    class Meta:
        verbose_name = _('week metric')
        verbose_name_plural = _('week metrics')

    def __unicode__(self):
        return _("'%(name)s' for week %(week)s of %(year)s") % {
            'name': self.metric.name,
            'week': self.created.strftime("%U"),
            'year': self.created.strftime("%Y")
        }


class MetricMonth(models.Model):
    """ Aggregation of Metrics on monthly basis """
    metric = models.ForeignKey(Metric, verbose_name=('metric'))
    num = models.BigIntegerField(_('number'), default=0)
    created = models.DateField(_('created'), default=datetime.date.today)

    class Meta:
        verbose_name = _('month metric')
        verbose_name_plural = _('month metrics')

    def __unicode__(self):
        return _("'%(name)s' for %(month)s %(year)s") % {
            'name': self.metric.name,
            'month': self.created.strftime("%B"),
            'year': self.created.strftime("%Y")
        }


class MetricYear(models.Model):
    """ Aggregation of Metrics on a yearly basis """
    metric = models.ForeignKey(Metric, verbose_name=_('metric'))
    num = models.BigIntegerField(_('number'), default=0)
    created = models.DateField(_('created'), default=datetime.date.today)

    class Meta:
        verbose_name = _('year metric')
        verbose_name_plural = _('year metrics')

    def __unicode__(self):
        return _("'%(name)s' for %(year)s") % {
            'name': self.metric.name,
            'year': self.created.strftime("%Y")
        }


class Gauge(models.Model):
    """
    A representation of the current state of some data.
    """
    name = models.CharField(_('name'), max_length=50)
    slug = models.SlugField(_('slug'), unique=True, max_length=60)
    current_value = models.DecimalField(_('current value'), max_digits=15, decimal_places=6, default='0.00')
    created = models.DateTimeField(_('created'), default=datetime.datetime.now)
    updated = models.DateTimeField(_('updated'), default=datetime.datetime.now)

    class Meta:
        verbose_name = _('gauge')
        verbose_name_plural = _('gauges')

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id and not self.slug:
            self.slug = slugify(self.name)

        self.updated = datetime.datetime.now()
        return super(Gauge, self).save(*args, **kwargs)

app_metrics/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext

@login_required
def metric_report_view(request):
    return render_to_response('app_metrics/reports.html', {}, context_instance=RequestContext(request))

app_metrics/templates/app_metrics/email.html
{% load i18n %}<html>
<body>
<h1>{% blocktrans with metric_set.name as name and today|date:"D d M Y" as date %}{{ name }} report for {{ date }}{% endblocktrans %}</h1>

<h2>{% trans "today so far"|capfirst %}</h2>
<table>
    {% for m in metrics %}
    <tr>
        <td>{{ m.metric.name }}</td>
        <td>{{ m.trends.current_day }}</td>
    </tr>
{% endfor %}
</table>

<h2>{% trans "yesterday"|capfirst %}</h2>
<table>
    <tr>
        <th></th>
        <th>{% trans "yesterday"|capfirst %}</th>
        <th>{% trans "prev week"|capfirst %}</th>
        <th>{% trans "prev month"|capfirst %}</th>
    </tr>
    {% for m in metrics %}
    <tr>
        <td>{{ m.metric.name }}</td>
        <td>{{ m.trends.yesterday.yesterday }}</td>
        <td>{{ m.trends.yesterday.previous_week }}</td>
        <td>{{ m.trends.yesterday.previous_month }}</td>
    </tr>
{% endfor %}
</table>

<h3>{% trans "week to date"|capfirst %}</h3>
<table>
    <tr>
        <th></th>
        <th>{% trans "week to date"|capfirst %}</th>
        <th>{% trans "last week"|capfirst %}</th>
        <th>{% trans "this week last month"|capfirst %}</th>
        <th>{% trans "this week last year"|capfirst %}</th>
    </tr>
    {% for m in metrics %}
    <tr>
        <td>{{ m.metric.name }}</td>
        <td>{{ m.trends.current_day }}</td>
        <td>{{ m.trends.week.week }}</td>
        <td>{{ m.trends.week.previous_week }}</td>
        <td>{{ m.trends.week.previous_month_week }}</td>
        <td>{{ m.trends.week.previous_year_week }}</td>
    </tr>
{% endfor %}
</table>

<h3>{% trans "month to date"|capfirst %}</h3>
<table>
    <tr>
        <th></th>
        <th>{% trans "month to date"|capfirst %}</th>
        <th>{% trans "last month"|capfirst %}</th>
        <th>{% trans "this month last year"|capfirst %}</th>
    </tr>
    {% for m in metrics %}
    <tr>
        <td>{{ m.metric.name }}</td>
        <td>{{ m.trends.month.month }}</td>
        <td>{{ m.trends.month.previous_month }}</td>
        <td>{{ m.trends.month.previous_year_month }}</td>
    </tr>
{% endfor %}
</table>

<h3>{% trans "year to date"|capfirst %}</h3>
<table>
    <tr>
        <th></th>
        <th>{% trans "year to date"|capfirst %}</th>
        <th>{% trans "last year"|capfirst %}</th>
    </tr>
    {% for m in metrics %}
    <tr>
        <td>{{ m.metric.name }}</td>
        <td>{{ m.trends.year.year }}</td>
        <td>{{ m.trends.year.previous_year }}</td>
    </tr>
{% endfor %}
</table>
</body>
</html>